### PR TITLE
Add EdDSA signature/verify with Ed25519 curve and ECDH-ES(+*) encryption with X25519 curve support

### PR DESCRIPTION
**Pull request by imirkin**
I haven't tested this with any external applications. jose does not support this. There are internal round-trip tests, but those just validate that we have an equal number of bugs on the encrypt/sign and decrypt/verify paths.

There's at least a node-based jose which does support it, but I haven't gotten around to figuring out how to operate it. Feedback welcome as always.

This addresses the 25519-curve-based part of #250. I think the 448 curve should probably wait until there are more "mainstream" implementations of it (i.e. x/crypto or stdlib).

### CODE REVIEW

**Comment by lestrrat** [comment]
I think we're okay to go ahead with merging this, but just as a precaution I think a slight clarification in the README that EdDSA and Ed25519 are experimental?

**Comment by imirkin** [comment]
README.md updated with notes on the new bits.

**Comment by lestrrat** [comment]
LGTM. Just waiting for the CI..

**Comment by lestrrat** [comment]
Merged. Thank you !

**Pull request merged**
