### PR TITLE
Add FAQ for Microsoft

### PR DESCRIPTION
**Pull request by johejo**
I think this issue is worth adding to the FAQ.
You can fix title or add any cool additional messages.

related #395

### CODE REVIEW

**Comment by johejo** [comment]
BTW, node-jsonwebtoken detects key's algorithm with this hack.
https://github.com/auth0/node-jsonwebtoken/blob/74d5719bd03993fcf71e3b176621f133eb6138c0/verify.js#L113-L118

**Comment by lestrrat** [comment]
I don't get how https://github.com/lestrrat-go/jwx/pull/465#issuecomment-920005781 has to do with #395?

**Comment by lestrrat** [comment]
Oh, the initial question was about JWKs, not IDToken vs AccessToken. I get it.
But no, no automatic algorithm choosing in this library. I would rather err on the side of safety

**Comment by johejo** [comment]
Don't worry about BTW comments.

> But no, no automatic algorithm choosing in this library. I would rather err on the side of safety

I agree.

I wondered why other libraries could validate Azure ID tokens with jwk without alg so easy and I suspected a vulnerability.
But it was magic for specs (and implementations) not vulnerabilities.

**Comment by lestrrat** [comment]
I suppose I _could_ add an option with a big warning:

```
jwt.Parse( ...., jwt.ThisOptionCouldMakeYourAppVulnerable(true))
```

I guess as long as the user can be made aware that they are risking something for ease of use, it could be added

**Comment by johejo** [comment]
Guessing based on kty may be somewhat safe.

Hmm, I'm just hoping that Microsoft will add alg.

**Comment by lestrrat** [comment]
I had an epiphany wrt to the `alg` situation. Please review if you are interested https://github.com/lestrrat-go/jwx/tree/infer-algorithm

**Pull request closed without merging**
