### PR TITLE
Fix building on 32-bit systems

### PR DESCRIPTION
**Pull request by ItalyPaleAle**
Builds on 32-bit systems are failing:

```
 /go/pkg/mod/github.com/lestrrat-go/jwx/v2@v2.0.21/jwt/openid/birthdate.go:69:7: math.MaxInt64 (untyped int constant 9223372036854775807) overflows int
```

This changes how 32-bit systems are detected in a way that doesn't cause the error. Although this does remove 16-bit systems from the `case`, the Go compiler does not support any 16-bit system at present (and it's very unlikely it ever will).

### CODE REVIEW

**Comment by ItalyPaleAle** [comment]
I'm not sure how to appease CodeQL at this point. It's a false positive but nothing I do seems to make it happy.

**Comment by lestrrat** [comment]
Thanks, but I'm a bit reluctant to merge something that I can't test.
Would you be able to provide a 32-bit environment smoke test, possibly by running a container or some such in GitHub Actions?

**Comment by ItalyPaleAle** [comment]
Sadly GH Actions runs on amd64, and Docker runs 64-bit containers on 64-bit operating systems like our laptops.

Simplest thing you can do to test this, if you're on a Linux box with `qemu-system-arm` and `qemu-user-binfmt` installed (this will be very slow):

```sh
cd examples
GOOS=linux GOARCH=arm GOARM=7 go test
```

The `go test` command above will fail when cross-compiling for armv7 (32-bit), during the build stage, with this error:

```
# github.com/lestrrat-go/jwx/v2/jwt/openid
../jwt/openid/birthdate.go:69:7: math.MaxInt64 (untyped int constant 9223372036854775807) overflows int
```

If you check out this PR, you'll see the build passes and the tests (running using emulation) work.

**Comment by lestrrat** [comment]
@ItalyPaleAle Well, I wanted to make sure I get to test and fix the CodeQL problem.
Also, I'm not talking about you or this PR, but I've had my share of I-trusted-the-PR-without-much-scrutiny-and-it-bit-me-later types of problems, so I'm being cautious here :)

Anyways. I see how you  verified the 32-bit compilation, so I've dug in and isolated the problem down to #1129 . This way there's no CodeQL shenanigans, and I think Go on 32-bit arch can compile it. Does this work for you?

**Comment by ItalyPaleAle** [comment]
Did not take it personally at all, your request was very valid and reasonable :)

#1129 LGTM and I think will fix the problem while making CodeQL happy. I'll close this PR. Thanks!

**Pull request closed without merging**
