### PR TITLE
Fix race in `jwk.AutoRefresh`

### PR DESCRIPTION
**Pull request by sergicastro**
Using the library I think I found a race when `AutoRefresh.Configure` and `AutoRefresh.doRefreshRequests` happen at the same time because both are accessing the `jwk.target` struct.

I added the first commit with a test that shows up the race, and then a commit that fixes this race.
I've been using the same locker I saw it is used in other points of the code, but maybe the best approach would be to have a locker for each instance of `jwk.target`.

### CODE REVIEW

**Comment by sergicastro** [comment]
@lestrrat  I installed go 1.16.x in my machine I run several times the command `make cover-goccy`, and even I used `-count` flag to identify if the test is flaky.

But I'm not able to make it fail, could you give me a hand so I can understand what's happening with that failed check?

**Comment by lestrrat** [comment]
@sergicastro Thank you! Let me think about this one. It might just be better if I could replace the current code with github.com/lestrrat-go/httprc

**Comment by lestrrat** [comment]
@sergicastro That's a flaky test that I've been meaning to fix. I know it's not great, but don't worry about it for now

**Comment by lestrrat** [comment]
For the record, I did a brief debugging session, and also pondered about httprc, but I think it would take a bit more time to come up with a solution, so we'll take the proposed fix until next time we have more time to debug/redesign throroughly

**Pull request merged**
