### PR TITLE
Implement OpenID Claims

### PR DESCRIPTION
**Pull request by lestrrat**
refs #112

### CODE REVIEW

**Comment by atotto** [comment]
LGTM+1

**Comment by lestrrat** [comment]
@repenno yes, hence https://github.com/lestrrat-go/jwx/pull/117/files#diff-57441ee290cf1771b339078fb2e93570R63

**Comment by lestrrat** [comment]
Still need to implement `.Set`

**Comment by wolfeidau** [comment]
Is there anything I can do to help get this completed?

Cheers

**Comment by lestrrat** [comment]
@wolfeidau I think I just ran out of steam. rebasing, fixing conflicts and seeing if things work in general would be great help

**Pull request closed without merging**
