### PR TITLE
Incorrect Parsing of Complete JWS JSON

### LINKED ISSUE #77: Incorrect Parsing of Complete JWS JSON
Similar issues to #70 

https://tools.ietf.org/html/rfc7515#appendix-A.6

I was trying to get coverage for protected header and key lookup in LookupSignature(kid string) and noticed a few things.

- While running t.Run("CompleteJSON", func(t *testing.T)..) I noticed that after unmarshal:

- Protected header structure was empty
- Header structure contained both protected and unprotected headers. 
- Entries were not delete from map
- Not checking length of map before assignment.

### PR DESCRIPTION
**Pull request by repenno**
fixes #77
- Please see issue for problem description
- message.go coverage is now ~100%

### CODE REVIEW

**Comment by repenno** [comment]
oh, headers.go is auto-generated. I will fix in main.go and add the comment on top like the others.

**Comment by lestrrat** [comment]
is this PR complete as of a139904?

**Comment by repenno** [comment]
Yes, it is complete

**Comment by lestrrat** [comment]
thanks!

**Pull request merged**
