### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by arpanetus**
becase => because

### CODE REVIEW

**Comment by arpanetus** [comment]
@lestrrat  I guess it works this time

**Comment by lestrrat** [comment]
Thanks. Your fix is correct, but you need to commit the result of running the code generation tool.
Run `go generate`, and commit the result, and the tests should pass.

**Comment by lestrrat** [comment]
Well, I woke up, so I'm just going to go ahead and do the last step, and merge your changes!

**Comment by lestrrat** [comment]
fixed via #434

Thanks for the PR!

**Pull request closed without merging**
