### PR TITLE
fix: add return error

### PR DESCRIPTION
**Pull request by orisano**
I added a return error to generated code of MarshalJSON.

I have a question. should I propagate of original error?

### CODE REVIEW

**Comment by lestrrat** [comment]
Oh, yes, the original error should be propagated! my bad.

**Comment by orisano** [comment]
Can we use %w? should we use errors.Wrapf?

**Comment by lestrrat** [comment]
Please use errors.Wrap for now. If we are going to use %w, we should change everything at once.

**Comment by orisano** [comment]
I fixed it

**Comment by lestrrat** [comment]
I went through #331 b/c the CI needed to be re-enabled, and files needed to be generated. Thanks.

**Pull request closed without merging**
